export const frequently_searched_words=[
  "clothing",
  "clothes",
  "fashion",
  "apparel",
  "outfits",
  "boutique",
  "online clothing",
  "clothing store",
  "clothing brands",
  "clothing sale",
  "discount clothing",
  "cheap clothes",
  "trendy clothes",
  "new arrivals",
  "womens clothing",
  "womens fashion",
  "dresses",
  "dress",
  "maxi dress",
  "mini dress",
  "midi dress",
  "summer dress",
  "winter dress",
  "tops for women",
  "top",
  "tops",
  "blouse",
  "blouses",
  "crop top",
  "crop tops",
  "bodysuit",
  "bodysuits",
  "skirt",
  "skirts",
  "jeans for women",
  "jeans",
  "leggings",
  "activewear women",
  "loungewear women",
  "plus size clothing",
  "plus size fashion",
  "plus size outfits",
  "womens jackets",
  "womens sweaters",
  "mens clothing",
  "mens fashion",
  "mens outfits",
  "t-shirt",
  "t-shirts",
  "tee",
  "tees",
  "shirt",
  "shirts",
  "hoodie",
  "hoodies",
  "sweatshirt",
  "sweatshirts",
  "mens jeans",
  "cargo pants",
  "joggers",
  "mens jackets",
  "mens coats",
  "dress shirt",
  "dress shirts",
  "mens blazers",
  "mens shorts",
  "athletic wear men",
  "loungewear men",
  "kids clothing",
  "childrens clothes",
  "toddler clothes",
  "baby clothes",
  "kids outfits",
  "school uniforms",
  "kids jackets",
  "kids shoes",
  "aesthetic outfits",
  "y2k clothing",
  "streetwear",
  "vintage clothing",
  "retro clothing",
  "minimalist fashion",
  "casual wear",
  "formal wear",
  "party outfits",
  "chic outfits",
  "elegant dresses",
  "trending fashion",
  "matching sets",
  "graphic tee",
  "graphic tees",
  "pants",
  "shorts",
  "sweaters",
  "jackets",
  "coats",
  "shoes",
  "sneakers",
  "heels",
  "boots",
  "sandals",
  "accessories",
  "handbags",
  "bags",
  "jewelry",
  "earrings",
  "necklace",
  "bracelets",
  "swimsuit",
  "swimsuits",
  "bikini",
  "bikinis",
  "lingerie",
  "underwear",
  "socks",
  "hats",
  "caps",
  "scarves",
  "sustainable clothing",
  "eco friendly fashion",
  "ethical clothing",
  "organic cotton",
  "handmade clothing",
  "thrift clothes",
  "second hand clothing",
  "resale clothing",
  "best clothes for summer",
  "cute outfits for school",
  "cheap trendy clothes online",
  "fashion outfits ideas",
  "outfits for work",
  "clothes for curvy body",
  "plus size trendy outfits",
  "outfits for parties",
  "streetwear outfits men",
  "streetwear outfits women",
  "winter outfits ideas",
  "summer tops for women"
]


